/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Catalog;
import model.VitalSignHistory;
import model.VitalSigns;

/**
 *
 * @author zhuzixuan
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    VitalSignHistory history;
    Catalog catalog;
    static int num=1;
            
    public CreateJPanel(VitalSignHistory history,Catalog catalog) {
        initComponents();
        this.history=history;
        this.catalog=catalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_title = new javax.swing.JLabel();
        lab_name = new javax.swing.JLabel();
        lab_ava = new javax.swing.JLabel();
        lab_type = new javax.swing.JLabel();
        lab_city_car = new javax.swing.JLabel();
        lab_manufacturer = new javax.swing.JLabel();
        lab_pro_date = new javax.swing.JLabel();
        lab_maintain_certi = new javax.swing.JLabel();
        lab_seat = new javax.swing.JLabel();
        lab_model = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_type = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        txt_manufacturer = new javax.swing.JTextField();
        txt_pro_date = new javax.swing.JTextField();
        txt_maintain_certi = new javax.swing.JTextField();
        txt_seat = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        comb_ava = new javax.swing.JComboBox<>();

        lab_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_title.setText("Create Car");

        lab_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_name.setText("Name:");

        lab_ava.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_ava.setText("Avaliable:");

        lab_type.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type.setText("Type:");

        lab_city_car.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_city_car.setText("City:");

        lab_manufacturer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_manufacturer.setText("Manufacturer:");

        lab_pro_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_pro_date.setText("Production Date(MM/DD/YYYY):");

        lab_maintain_certi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_maintain_certi.setText("Maintenance Certificate:");

        lab_seat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_seat.setText("Number of Seat:");

        lab_model.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_model.setText("Model Number:");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_typeActionPerformed(evt);
            }
        });

        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        txt_manufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manufacturerActionPerformed(evt);
            }
        });

        txt_pro_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pro_dateActionPerformed(evt);
            }
        });

        txt_maintain_certi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maintain_certiActionPerformed(evt);
            }
        });

        txt_seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seatActionPerformed(evt);
            }
        });

        txt_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modelActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        comb_ava.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_model, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_seat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_pro_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_manufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_city_car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_ava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_maintain_certi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_ava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pro_date, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maintain_certi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_seat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save)
                .addGap(507, 507, 507))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lab_title)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_ava, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_ava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_type, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_city_car, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_pro_date, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pro_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_maintain_certi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maintain_certi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_seat)
                    .addComponent(txt_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_model)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btn_save)
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_typeActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_manufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manufacturerActionPerformed

    private void txt_pro_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pro_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pro_dateActionPerformed

    private void txt_maintain_certiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maintain_certiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maintain_certiActionPerformed

    private void txt_seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seatActionPerformed

    private void txt_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modelActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
       // TODO add your handling code here:
       
        String Name=txt_name.getText();
        boolean Ava=Boolean.parseBoolean("true");
        if(comb_ava.getSelectedItem().equals("no")){
            Ava=Boolean.parseBoolean("false");
            //boolean Ava=True;
        }
        //boolean Ava=Boolean.parseBoolean(txt.);
        String Type=txt_type.getText();
        String City_Car=txt_city.getText();
        String Manufacturer=txt_manufacturer.getText();
        String Product_Date=txt_pro_date.getText();
        String Maintain_Certi=txt_maintain_certi.getText();
        int Seat=0;
        if(txt_seat.getText().isEmpty()){
            Seat=0;
        }
        else{
            Seat=Integer.parseInt(txt_seat.getText());

        }
        //int Seat=Integer.parseInt(txt_seat.getText());
        String Model_num=txt_model.getText();
        int Serial_num=num++;
        
        while(true){
//        if(txt_city.getText().isEmpty()||txt_maintain_certi.getText().length()==0||txt_manufacturer.getText().length()==0||txt_model.getText().length()==0||txt_name.getText().length()==0||txt_pro_date.getText().length()==0||txt_seat.getText().length()==0||txt_type.getText().length()==0){
//            JOptionPane.showMessageDialog(this,"Please enter information!");
//            break;
//        }
        if(Type.isEmpty()||City_Car.isEmpty()||Manufacturer.isEmpty()||Product_Date.isEmpty()||Maintain_Certi.isEmpty()||Seat==0||Model_num.isEmpty()){
                        JOptionPane.showMessageDialog(this,"Please enter information!");
            break;
        }
        else if(txt_pro_date.getText().length()!=8||!isNumeric(txt_pro_date.getText())){
            JOptionPane.showMessageDialog(this,"Please enter correct Production Date!");
            break;
        }
        else if(!isNumeric(txt_seat.getText())||Integer.valueOf(txt_seat.getText()).intValue()<0){
            JOptionPane.showMessageDialog(this,"Please enter correct seat number!");
            break;
        }
        else{
        VitalSigns vs=history.addNewVitals();
        
        vs.setName(Name);
        vs.setAva(Ava);
        vs.setType(Type);
        vs.setCity_Car(City_Car);
        vs.setManufacturer(Manufacturer);
        vs.setProduct_Date(Product_Date);
        vs.setMaintain_Certi(Maintain_Certi);
        vs.setModel_num(Model_num);
        vs.setSeat(Seat);
        vs.setSerial_num(Serial_num);
        
        catalog.setTime();
        //showDialog
        JOptionPane.showMessageDialog(this,"save!");
        break;}
        }
        
        txt_city.setText("");
        txt_maintain_certi.setText("");
        txt_manufacturer.setText("");
        txt_model.setText("");
        txt_name.setText("");
        txt_pro_date.setText("");
        txt_seat.setText("");
        txt_type.setText("");
        comb_ava.setSelectedItem("yes");
        
    }//GEN-LAST:event_btn_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> comb_ava;
    private javax.swing.JLabel lab_ava;
    private javax.swing.JLabel lab_city_car;
    private javax.swing.JLabel lab_maintain_certi;
    private javax.swing.JLabel lab_manufacturer;
    private javax.swing.JLabel lab_model;
    private javax.swing.JLabel lab_name;
    private javax.swing.JLabel lab_pro_date;
    private javax.swing.JLabel lab_seat;
    private javax.swing.JLabel lab_title;
    private javax.swing.JLabel lab_type;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_maintain_certi;
    private javax.swing.JTextField txt_manufacturer;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pro_date;
    private javax.swing.JTextField txt_seat;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables

    public static boolean isNumeric(String str){  
        for (int i = str.length();--i>=0;){    
            if (!Character.isDigit(str.charAt(i))){  
                return false;  
            }  
        }  
        return true;  
    }  
}
