/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageSuppliers.java
 *
 * Created on Oct 1, 2011, 11:09:26 AM
 */

package ui.ViewAll;

import ui.admin.*;
import model.Community;
import model.CommunityDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;



/**
 *
 * @author Rushabh
 */
public class ViewAll extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CommunityDirectory supplierDirectory;
    private EncounterHistory encounterHistory;
    
    /** Creates new form ManageSuppliers */
    public ViewAll(JPanel upc, CommunityDirectory sd,EncounterHistory eh) {
        initComponents();
        userProcessContainer = upc;
        supplierDirectory = sd;
        encounterHistory=eh;
        refreshTable();
    }
    
    public void refreshTable() {
        
        DefaultTableModel model_s = (DefaultTableModel)tblSuppliers.getModel();
        model_s.setRowCount(0);
        
        for(Community s : supplierDirectory.getSupplierList()) {
            Object row[] = new Object[2];
            row[0] = s;
            //row[1]= s.getPatientCatalog().getNum();
            row[1]=s.getPatientCatalog().getPatientsSize();
           // row[1] = s.getProductCatalog().getProductCount() == 0 ? "None" : s.getProductCatalog().getProductCount();
            model_s.addRow(row);
        }
        
        DefaultTableModel model_e = (DefaultTableModel)tblEncounter.getModel();
        model_e.setRowCount(0);
        for(Encounter e : encounterHistory.getEncounterList()) {
            Object row[] = new Object[2];
            row[0] = e;
            row[1]=e.getVitalSigns().getDate();
           // row[1] = s.getProductCatalog().getProductCount() == 0 ? "None" : s.getProductCatalog().getProductCount();
            model_e.addRow(row);
        }
    }
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        lblSupplierList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEncounter = new javax.swing.JTable();
        lblSupplierList1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(185, 212, 232));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        tblSuppliers.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Community Name", "Abnormal blood pressure people num"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSuppliers);

        lblSupplierList.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lblSupplierList.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierList.setText("The total number people in the community with abnormal blood pressure");

        tblEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEncounter);

        lblSupplierList1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lblSupplierList1.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierList1.setText("Encounter Catalog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierList1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                        .addComponent(lblSupplierList)
                        .addComponent(jScrollPane2)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSupplierList)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSupplierList1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSupplierList;
    private javax.swing.JLabel lblSupplierList1;
    private javax.swing.JTable tblEncounter;
    private javax.swing.JTable tblSuppliers;
    // End of variables declaration//GEN-END:variables

}
