/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.image.ImageFilter;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.MimetypesFileTypeMap;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.*;
import model.Person;

/**
 *
 * @author zhuzixuan
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateInof
     */
    
    Person person;
    JFileChooser fc;
    MimetypesFileTypeMap mtftp;
    public CreateJPanel(Person person) {
        initComponents();
        this.person=person;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_birth = new javax.swing.JTextField();
        txt_geo = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_fax = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_secnum = new javax.swing.JTextField();
        txt_mednum = new javax.swing.JTextField();
        txt_healthnum = new javax.swing.JTextField();
        txt_bank = new javax.swing.JTextField();
        txt_certi = new javax.swing.JTextField();
        txt_vehnum = new javax.swing.JTextField();
        txt_linkedln = new javax.swing.JTextField();
        txt_device = new javax.swing.JTextField();
        txt_interadd = new javax.swing.JTextField();
        txt_face = new javax.swing.JTextField();
        txt_bio = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        txt_other = new javax.swing.JTextField();
        btn_face = new javax.swing.JButton();
        btn_bio = new javax.swing.JButton();
        label_face = new javax.swing.JLabel();
        label_bio = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create");
        jLabel1.setToolTipText("");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Geographic data");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Date of birth");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Telephone numbers");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("FAX number");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Email addresses");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Social Security number");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Medical record number");

        jLabel10.setText("Health plan beneficiary number");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Bank account numbers");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Certificate/license number");

        jLabel13.setText("Vehicle identifiers and serial numbers including license plates");

        jLabel14.setText("Device identifiers and serial numbers");

        jLabel15.setText("LinkedIn");

        jLabel16.setText("Internet protocol addresses");

        jLabel17.setText("Biometric identifiers (i.e. retinal scan, fingerprints)");

        jLabel18.setText("Full face photos and comparable images");

        jLabel19.setText("Any unique identifying number, characteristic, or code");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_birthActionPerformed(evt);
            }
        });

        txt_geo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_geoActionPerformed(evt);
            }
        });

        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });

        txt_fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faxActionPerformed(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txt_secnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_secnumActionPerformed(evt);
            }
        });

        txt_mednum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mednumActionPerformed(evt);
            }
        });

        txt_healthnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_healthnumActionPerformed(evt);
            }
        });

        txt_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bankActionPerformed(evt);
            }
        });

        txt_certi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_certiActionPerformed(evt);
            }
        });

        txt_vehnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vehnumActionPerformed(evt);
            }
        });

        txt_linkedln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_linkedlnActionPerformed(evt);
            }
        });

        txt_device.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deviceActionPerformed(evt);
            }
        });

        txt_interadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_interaddActionPerformed(evt);
            }
        });

        txt_face.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faceActionPerformed(evt);
            }
        });

        txt_bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bioActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        txt_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otherActionPerformed(evt);
            }
        });

        btn_face.setText("choose a pic");
        btn_face.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faceActionPerformed(evt);
            }
        });

        btn_bio.setText("choose a pic");
        btn_bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bioActionPerformed(evt);
            }
        });

        label_face.setSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_geo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_birth))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_certi)
                                        .addComponent(txt_bank)
                                        .addComponent(txt_email)
                                        .addComponent(txt_mednum)
                                        .addComponent(txt_secnum)
                                        .addComponent(txt_healthnum)
                                        .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_vehnum, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_other, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                .addComponent(txt_linkedln)
                                .addComponent(txt_interadd))
                            .addComponent(txt_device, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_face))
                                .addComponent(txt_face, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_bio, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_bio))
                            .addComponent(label_face, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_bio, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(btn_face))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_geo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_face, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_secnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_mednum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_healthnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_certi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(label_face, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bio))
                        .addGap(0, 0, 0)
                        .addComponent(txt_bio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_vehnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14)
                        .addGap(0, 0, 0)
                        .addComponent(txt_device, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15)
                        .addGap(0, 0, 0)
                        .addComponent(txt_linkedln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel19)
                        .addGap(0, 0, 0)
                        .addComponent(txt_other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel16)
                        .addGap(0, 0, 0)
                        .addComponent(txt_interadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_bio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_birthActionPerformed

    private void txt_geoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_geoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_geoActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed

    private void txt_faxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_faxActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_secnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_secnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_secnumActionPerformed

    private void txt_mednumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mednumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mednumActionPerformed

    private void txt_healthnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_healthnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_healthnumActionPerformed

    private void txt_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bankActionPerformed

    private void txt_certiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_certiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_certiActionPerformed

    private void txt_vehnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vehnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vehnumActionPerformed

    private void txt_linkedlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_linkedlnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_linkedlnActionPerformed

    private void txt_deviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deviceActionPerformed

    private void txt_interaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_interaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_interaddActionPerformed

    private void txt_faceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_faceActionPerformed

    private void txt_bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bioActionPerformed

    private void txt_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otherActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        Set<String> typeSet=new HashSet<>();
        typeSet.add(".jpg");
        typeSet.add(".png");
        typeSet.add(".gif");
        int f=txt_face.getText().lastIndexOf(".");
        int b=txt_bio.getText().lastIndexOf(".");
        String face=txt_face.getText().substring(f);
        String bio=txt_bio.getText().substring(b);
        while(true){
        if(txt_name.getText().length()==0||txt_birth.getText().length()==0||txt_email.getText().length()==0||txt_bank.getText().length()==0
                ||txt_certi.getText().length()==0||txt_device.getText().length()==0||txt_fax.getText().length()==0||txt_geo.getText().length()==0
                ||txt_healthnum.getText().length()==0||txt_interadd.getText().length()==0||txt_linkedln.getText().length()==0||txt_mednum.getText().length()==0
                ||txt_other.getText().length()==0||txt_secnum.getText().length()==0||txt_tel.getText().length()==0||txt_vehnum.getText().length()==0
                ||txt_face.getText().length()==0||txt_bio.getText().length()==0){
           
            JOptionPane.showMessageDialog(this, "Information is not completed");
            break;
        }
        else if(txt_birth.getText().length()!=8){
            JOptionPane.showMessageDialog(this, "Birth Data is invalid");
            break;
        }
        else if(txt_bank.getText().length()!=10){
            JOptionPane.showMessageDialog(this, "Bank number is invalid");
            break;
        }
        else if(txt_fax.getText().length()!=8){
            JOptionPane.showMessageDialog(this, "Fax number is invalid");
            break;
        }
        else if(txt_secnum.getText().length()!=9){
            JOptionPane.showMessageDialog(this, "SSN is invalid");
            break;
        }
        else if(txt_tel.getText().length()!=10){
            JOptionPane.showMessageDialog(this, "Telephone number is invalid");
            break;
        }
        else if(!typeSet.contains(f)||!typeSet.contains(b)){
            JOptionPane.showMessageDialog(this, "Images are invalid");
            break;
        }
        else{
        person.setName(txt_name.getText());
        person.setBirth(txt_birth.getText());
        person.setEmail(txt_email.getText());
        person.setBank_num(txt_bank.getText());         //less than 10
        person.setCerti_num(txt_certi.getText());
        person.setDevice_num(txt_device.getText());
        person.setFax_num(txt_fax.getText());       //less than 8
        person.setGeo_data(txt_geo.getText());
        person.setHealth_num(txt_healthnum.getText());
        person.setIntnet_add(txt_interadd.getText());
        person.setLinkedln(txt_linkedln.getText());
        person.setMedical_num(txt_mednum.getText());
        person.setOther_num(txt_other.getText());
        person.setSecur_num(txt_secnum.getText());      //less than 9
        person.setTel(txt_tel.getText());       //less than 10
        person.setVehc_num(txt_vehnum.getText());
        person.setBio_pic_add(fc.getSelectedFile().getAbsolutePath());
        person.setFace_add(fc.getSelectedFile().getAbsolutePath());//

        JOptionPane.showMessageDialog(this, "Personal Information saved!");
        break;
        }}
        
                
    }//GEN-LAST:event_saveActionPerformed

    private void btn_faceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faceActionPerformed
        // TODO add your handling code here:
        int width=150, height=150;
        
        if(fc==null){
            fc=new JFileChooser();
        }
        fc.setCurrentDirectory(new java.io.File("/Users/zhuzixuan/NEU/INFO5100/images"));
        fc.setDialogTitle("Please choose an face image");
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        if(fc.showOpenDialog(btn_face)==JFileChooser.APPROVE_OPTION){
            txt_face.setText(fc.getSelectedFile().getAbsolutePath());
            ImageIcon img=new ImageIcon(txt_face.getText());
            img.setImage(img.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
            label_face.setIcon(img);
           
        }
        //txt_face.setText(fc.getSelectedFile().getAbsolutePath());
        //person.setFace_add(fc.getSelectedFile().getAbsolutePath());
        
        
    }//GEN-LAST:event_btn_faceActionPerformed

    private void btn_bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bioActionPerformed
        // TODO add your handling code here:
        int width=150, height=150;
        if(fc==null){
            fc=new JFileChooser();
        }
        fc.setCurrentDirectory(new java.io.File("/Users/zhuzixuan/NEU/INFO5100/images"));
        fc.setDialogTitle("Please choose an face image");
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if(fc.showOpenDialog(btn_bio)==JFileChooser.APPROVE_OPTION){
            txt_bio.setText(fc.getSelectedFile().getAbsolutePath());
            ImageIcon img=new ImageIcon(txt_bio.getText());
            img.setImage(img.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
            label_bio.setIcon(img);
        }
        //int returnVal=fc.showOpenDialog(CreateJPanel.this);
        
    }//GEN-LAST:event_btn_bioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bio;
    private javax.swing.JButton btn_face;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_bio;
    private javax.swing.JLabel label_face;
    private javax.swing.JButton save;
    private javax.swing.JTextField txt_bank;
    private javax.swing.JTextField txt_bio;
    private javax.swing.JTextField txt_birth;
    private javax.swing.JTextField txt_certi;
    private javax.swing.JTextField txt_device;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_face;
    private javax.swing.JTextField txt_fax;
    private javax.swing.JTextField txt_geo;
    private javax.swing.JTextField txt_healthnum;
    private javax.swing.JTextField txt_interadd;
    private javax.swing.JTextField txt_linkedln;
    private javax.swing.JTextField txt_mednum;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_other;
    private javax.swing.JTextField txt_secnum;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_vehnum;
    // End of variables declaration//GEN-END:variables
}
